stages:
  - build-rntest

stages:
  - other

custom-build-rntest:
  image: node:12
  stage: build-rntest 
  script: cd ./packages/rntest && npm run build 
  only:
    changes:
      - packages/rntest/**/*
      - .gitlab-ci.yml


other-stages:
 script: echo "other-stages" 
 stage: other