stages:
  - build
  - check

include: '.gitlab-ci-web-app.yml'

variables:
  DANGER_GITLAB_API_TOKEN: 'Q7-nZ4pUkL_UtcP4zHLt'

custom-build-rntest:
  image: node:12
  stage: build
  script: cd ./packages/rntest && npm run build 
  only:
    changes:
      - packages/rntest/**/*
      - .gitlab-ci.yml

other-stages-on-build-rntest:
 script: echo "other-stages on-build-rntest" 
 stage: build


danger-eslint-jest-check:
  image: node:12
  stage: check
  script:
    - echo startDangerScript
    - npx danger ci --failOnErrors -v
  only:
    - merge_requests

