stages:
  - build

include: './.gitlab-ci-web-app.yml'

custom-build-rntest:
  image: node:12
  stage: build
  script: cd ./packages/rntest && npm run build 
  only:
    changes:
      - packages/rntest/**/*
      - .gitlab-ci.yml

other-stages-on-build-rntest:
 script: echo "other-stages on-build-rntest" 
 stage: build


